envVars:
- name: ROX_VULN_MGMT_UI
  value: "true"
- name: ROX_DACKBOX
  value: "true"
- name: ROX_POD_DEPLOY_SEPARATE
  value: "true"
- name: ROX_ROCKSDB
  value: "false"
- name: ROX_ADMISSION_CONTROL_ENFORCE_ON_UPDATE
  value: "true"
- name: ROX_DRY_RUN_JOB
  value: "true"
- name: ROX_BOOLEAN_POLICY_LOGIC
  value: "false"
- name: ROX_POLICY_IMPORT_EXPORT
  value: "false"
- name: ROX_ANALYST_NOTES_UI
  value: "true"
- name: ROX_EVENT_TIMELINE_UI
  value: "true"
- name: ROX_REQUIRED_IMAGE_LABEL_POLICY
  value: "true"
- name: ROX_ADMISSION_CONTROL_SERVICE
  value: "true"
