cluster:
  name: null # string
  type: null # string

endpoint:
  central: null # string
  advertised: null # string

image:
  repository:
    main: null # string
    collector: null # string
  registry:
    main: null # string
    collector: null # string
  pullPolicy:
    main: null # string
    collector: null # string
  tag:
    main: null # string
    collector: null # string

imagePullSecrets:
  useExisting: null # string | [string]

mainImagePullSecrets:
  useExisting: null # string | [string]

collectorImagePullSecrets:
  useExisting: null # string | [string]

config:
  collectionMethod: null # string
  admissionControl:
    createService: null # bool
    listenOnUpdates: null # bool
    enableService: null # bool
    enforceOnUpdates: null # bool
    scanInline: null # bool
    disableBypass: null # bool
    timeout: null # number
  registryOverride: null # string
  disableTaintTolerations: null # bool
  createUpgraderServiceAccount: null # bool
  createSecrets: null # bool
  offlineMode: null # bool
  slimCollector: null # bool
  sensorResources: null # dict
  admissionControlResources: null # dict
  collectorResources: null # dict
  complianceResources: null # dict
  exposeMonitoring: null # bool

envVars: null # [obj]
