# Configuration for Repo Lockdown

# Skip issues and pull requests created before a given timestamp. Timestamp must
# follow ISO 8601 (`YYYY-MM-DD`). Set to `false` to disable
skipCreatedBefore: false


# Comment to post before closing or locking. Set to `false` to disable
comment: true

# Label to add before closing or locking. Set to `false` to disable
label: false

# Close issues and pull requests
close: true

# Lock issues and pull requests
lock: true

pulls:
  comment: >
    Thank you for your contribution. Unfortunately, bots manage this repository. For enhancement requests and issues, please get in touch with humans at https://support.stackrox.com/. We look forward to hearing from you.
  lock: true
