clusterName: null # string
centralEndpoint: null # string
registryOverride: null # string
exposeMonitoring: null # bool
createUpgraderServiceAccount: null # string
helmManaged: null
createSecrets: null
additionalCAs: null # [obj]
imagePullSecrets:
  username: null # string
  password: null # string
  allowNone: null # bool
  useExisting: null # string | [string]
  useFromDefaultServiceAccount: null # bool
mainImagePullSecrets:
  username: null # string
  password: null # string
  useExisting: null # string | [string]
  useFromDefaultServiceAccount: null # bool
  allowNone: null # bool
collectorImagePullSecrets:
  username: null # string
  password: null # string
  useExisting: null # string | [string]
  useFromDefaultServiceAccount: null # bool
  allowNone: null # bool
image:
  registry: null # string
  main:
    registry: null # string
    name: null # string
    tag: null # string
    fullRef: null # string
    pullPolicy: null # string
  collector:
    registry: null # string
    name: null # string
    tag: null # string
    fullRef: null # string
    pullPolicy: null # string
env:
  openshift: null # bool
  istio: null # bool
ca:
  cert: null # string
sensor:
  imagePullPolicy: null # string
  endpoint: null # string
  resources: null # string | dict
  serviceTLS:
    cert: null # string
    key: null # string
admissionControl:
  enable: null # bool
  listenOnUpdates: null # bool
  dynamic:
    enforce: null # bool
    scanInline: null # bool
    disableBypass: null # bool
    timeout: null # natural number
    enforceOnUpdates: null # bool
  imagePullPolicy: null # string
  resources: null # string | dict
  serviceTLS:
    cert: null # string
    key: null # string
collector:
  collectionMethod: null # string
  disableTaintTolerations: null # bool
  slimMode: null # bool
  imagePullPolicy: null # string
  resources: null # string | dict
  complianceImagePullPolicy: null # string
  complianceResources: null # string | dict
  serviceTLS:
    cert: null # string
    key: null # string
customize:
  labels: {} # dict
  annotations: {} # dict
  podLabels: {} # dict
  podAnnotations: {} # dict
  envVars: {} # dict
  sensor:
    labels: {} # dict
    annotations: {} # dict
    podLabels: {} # dict
    podAnnotations: {} # dict
    envVars: {} # dict
  admission-control:
    labels: {} # dict
    annotations: {} # dict
    podLabels: {} # dict
    podAnnotations: {} # dict
    envVars: {} # dict
  collector:
    labels: {} # dict
    annotations: {} # dict
    podLabels: {} # dict
    podAnnotations: {} # dict
    envVars: {} # dict
  other: {} # dict
allowNonstandardNamespace: null # bool
allowNonstandardReleaseName: null # bool
meta:
  useLookup: null # bool
  fileOverrides: {} # dict
  apiServer:
    version: null # string
    overrideAPIResources: null # [string]
    extraAPIResources: null # [string]
