
envVars:
- name: ROX_ACTIVE_VULN_MANAGEMENT
  value: "true"
- name: ROX_COLLECTOR_ALT_PROBE_DOWNLOAD
  value: "false"
- name: ROX_COMPLIANCE_IN_ROCKSDB
  value: "true"
- name: ROX_COMPLIANCE_OPERATOR_INTEGRATION
  value: "true"
- name: ROX_CSV_EXPORT
  value: "false"
- name: ROX_ENABLE_ROLLBACK
  value: "true"
- name: ROX_INTEGRATIONS_AS_CONFIG
  value: "false"
- name: ROX_NETWORK_DETECTION_BASELINE_SIMULATION
  value: "true"
- name: ROX_NETWORK_DETECTION_BLOCKED_FLOWS
  value: "false"
- name: ROX_SCOPED_ACCESS_CONTROL_V2
  value: "true"
