
envVars:
- name: ROX_COMPLIANCE_IN_ROCKSDB
  value: "true"
- name: ROX_CSV_EXPORT
  value: "false"
- name: ROX_ENABLE_ROLLBACK
  value: "true"
- name: ROX_INACTIVE_IMAGE_SCANNING_UI
  value: "true"
- name: ROX_INTEGRATIONS_AS_CONFIG
  value: "false"
- name: ROX_K8S_AUDIT_LOG_DETECTION
  value: "false"
- name: ROX_NETWORK_DETECTION_BASELINE_SIMULATION
  value: "false"
- name: ROX_NETWORK_DETECTION_BASELINE_VIOLATION
  value: "true"
- name: ROX_NETWORK_DETECTION_BLOCKED_FLOWS
  value: "false"
- name: ROX_SCOPED_ACCESS_CONTROL_V2
  value: "false"
- name: ROX_SENSOR_INSTALLATION_EXPERIENCE
  value: "true"
- name: ROX_SENSOR_TLS_CHALLENGE
  value: "true"
