apiVersion: v1
data:
  {{- range $path, $bytes := .Files.Glob "secrets/additional-cas" }}
  {{ base $path }}: '{{ b64enc $bytes }}'
  {{ end }}
kind: Secret
metadata:
  labels:
    auto-upgrade.stackrox.io/component: sensor
  name: additional-ca
  namespace: stackrox
type: Opaque
