{{- include "srox.init" . -}}

{{ if and ._rox.admissionControl.enable ._rox.admissionControl.exposeMonitoring }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: admission-control-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "networkpolicy" "admission-control-monitoring") | nindent 4 }}
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    {{- include "srox.annotations" (list . "networkpolicy" "admission-control-monitoring") | nindent 4 }}
spec:
  ingress:
  - ports:
    - port: 9090
      protocol: TCP
  podSelector:
    matchLabels:
      app: admission-control
  policyTypes:
    - Ingress
{{ end }}
