{{- include "srox.init" . -}}

{{- if and ._rox.admissionControl.enable (ne ._rox.ca._cert "") (ne ._rox.admissionControl.serviceTLS._cert "") (ne ._rox.admissionControl.serviceTLS._key "") }}
apiVersion: v1
kind: Secret
data:
  ca.pem: |
    {{- ._rox.ca._cert | b64enc | nindent 4 }}
  admission-control-cert.pem: |
    {{- ._rox.admissionControl.serviceTLS._cert | b64enc | nindent 4 }}
  admission-control-key.pem: |
    {{- ._rox.admissionControl.serviceTLS._key | b64enc | nindent 4 }}
metadata:
  labels:
    {{- include "srox.labels" (list . "secret" "admission-control-tls") | nindent 4 }}
    auto-upgrade.stackrox.io/component: sensor
  annotations:
    {{- include "srox.annotations" (list . "secret" "admission-control-tls") | nindent 4 }}
  name: admission-control-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
