{{- include "srox.init" . -}}

{{- if and (ne ._rox.ca._cert "") (ne ._rox.collector.serviceTLS._cert "") (ne ._rox.collector.serviceTLS._key "") }}
apiVersion: v1
kind: Secret
data:
  ca.pem: |
    {{- ._rox.ca._cert | b64enc | nindent 4 }}
  collector-cert.pem: |
    {{- ._rox.collector.serviceTLS._cert | b64enc | nindent 4 }}
  collector-key.pem: |
    {{- ._rox.collector.serviceTLS._key | b64enc | nindent 4 }}
metadata:
  labels:
    {{- include "srox.labels" (list . "secret" "collector-tls") | nindent 4 }}
    auto-upgrade.stackrox.io/component: sensor
  annotations:
    {{- include "srox.annotations" (list . "secret" "collector-tls") | nindent 4 }}
  name: collector-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
