{{- include "srox.init" . -}}

{{- if and (ne ._rox.ca._cert "") (ne ._rox.sensor.serviceTLS._cert "") (ne ._rox.sensor.serviceTLS._key "") }}
apiVersion: v1
kind: Secret
data:
  ca.pem: |
    {{- ._rox.ca._cert | b64enc | nindent 4 }}
  sensor-cert.pem: |
    {{- ._rox.sensor.serviceTLS._cert | b64enc | nindent 4 }}
  sensor-key.pem: |
    {{- ._rox.sensor.serviceTLS._key | b64enc | nindent 4 }}
metadata:
  labels:
    {{- include "srox.labels" (list . "secret" "sensor-tls") | nindent 4 }}
    auto-upgrade.stackrox.io/component: sensor
  annotations:
    {{- include "srox.annotations" (list . "secret" "sensor-tls") | nindent 4 }}
  name: sensor-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
