name: Update repository README file

on: [push]

jobs:
  copyFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Checking for a README file in the last commit"
          if FILEPATH=$(git diff --name-only HEAD~1 HEAD | grep README); then
            echo "Found updated README"
            cp -vp "$FILEPATH" README.md
            echo "Updated README"
          else
            echo "Cannout find README"
          fi
      - run: echo "Done"
